import { randomUUID } from "node:crypto";
import { appendFile, lstat, mkdir, open, readFile, rename, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { normalizeRunGoal, type RepositoryIdentity } from "./repository-identity";
import type { ExecutionProfileId, RiqorRun, RiqorRunStatus, RiqorTraceEvent, RiqorTraceEventStatus, RiqorTraceEventType, RiqorTraceMetadataValue } from "./types";
import type { HarnessPathId } from "../../plugins/codex-self-improvement/hooks/paths";

const runIdPattern=/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/; const digestPattern=/^[a-f0-9]{64}$/; const metadataKeyPattern=/^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$/; const defaultLockTimeoutMs=1000; const defaultStaleLockMs=30000; const lockRetryMs=20;
export type RunLocation=Readonly<{stateRoot:string;identity:RepositoryIdentity;runId:string}>;
export type CreateRunOptions=Readonly<{stateRoot:string;identity:RepositoryIdentity;goal:string;pathId:HarnessPathId;profileId:ExecutionProfileId;parentRunId?:string;now?:Date;randomId?:()=>string}>;
export type AppendRunEventOptions=RunLocation & Readonly<{source:RiqorTraceEvent["source"];type:RiqorTraceEventType;status:RiqorTraceEventStatus;subject?:string;digest?:string;evidenceRefs?:readonly string[];metadata?:Readonly<Record<string,RiqorTraceMetadataValue>>;nextStatus?:RiqorRunStatus;now?:Date;randomId?:()=>string;lockTimeoutMs?:number;staleLockMs?:number}>;
export type TransitionRunOptions=RunLocation & Readonly<{status:RiqorRunStatus;now?:Date;lockTimeoutMs?:number;staleLockMs?:number}>;
export type CompleteRunOptions=RunLocation & Readonly<{now?:Date;randomId?:()=>string;lockTimeoutMs?:number;staleLockMs?:number}>;
type ActivePointer=Readonly<{schemaVersion:1;runId:string}>; type LockOptions=Readonly<{timeoutMs?:number;staleMs?:number}>;
function projectDirectory(stateRoot:string,rootDigest:string){return join(stateRoot,"projects",rootDigest)} function runsDirectory(stateRoot:string,rootDigest:string){return join(projectDirectory(stateRoot,rootDigest),"runs")} function runDirectory(stateRoot:string,rootDigest:string,runId:string){return join(runsDirectory(stateRoot,rootDigest),runId)} function activePath(stateRoot:string,rootDigest:string){return join(projectDirectory(stateRoot,rootDigest),"active.json")}
function validateRootDigest(value:string){if(!digestPattern.test(value)) throw new Error("invalid repository digest")} function validateRunId(value:string){if(!runIdPattern.test(value)) throw new Error("invalid run id")}
function boundedText(value:string,label:string,maximum:number){if(Array.from(value).length>maximum) throw new Error(`${label} is too long`); if(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(value)) throw new Error(`${label} contains unsupported control characters`); return value}
function validateEventInput(options:AppendRunEventOptions){if(options.subject!==undefined) boundedText(options.subject,"event subject",256); if(options.digest!==undefined&&!digestPattern.test(options.digest)) throw new Error("invalid event digest"); if(options.evidenceRefs&&options.evidenceRefs.length>32) throw new Error("too many evidence references"); for(const reference of options.evidenceRefs??[]) boundedText(reference,"evidence reference",128); const entries=Object.entries(options.metadata??{}); if(entries.length>32) throw new Error("too many event metadata entries"); for(const [key,value] of entries){if(!metadataKeyPattern.test(key)) throw new Error("invalid event metadata key"); if(typeof value==="string") boundedText(value,"event metadata value",512); if(typeof value==="number"&&!Number.isFinite(value)) throw new Error("invalid event metadata number")}}
function publicRepository(identity:RepositoryIdentity):RiqorRun["repository"]{validateRootDigest(identity.rootDigest);return Object.freeze({rootDigest:identity.rootDigest,headSha:identity.headSha,dirty:identity.dirty})}
async function existingFileKind(path:string){try{return await lstat(path)}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT") return null; throw error}}
async function assertSafeRegularFile(path:string,allowMissing=false){const entry=await existingFileKind(path); if(!entry){if(allowMissing)return false;throw new Error("state file not found")} if(entry.isSymbolicLink()) throw new Error("unsafe symlink state path"); if(!entry.isFile()) throw new Error("unsafe non-file state path"); return true}
async function readTextFile(path:string){await assertSafeRegularFile(path);return readFile(path,"utf8")}
async function writeJsonAtomic(path:string,value:unknown){await mkdir(dirname(path),{recursive:true,mode:0o700}); await assertSafeRegularFile(path,true); const temporary=`${path}.${process.pid}.${randomUUID()}.tmp`; try{await writeFile(temporary,`${JSON.stringify(value)}\n`,{encoding:"utf8",mode:0o600,flag:"wx"});await rename(temporary,path)}finally{await rm(temporary,{force:true})}}
function sleep(ms:number){return new Promise<void>(resolve=>setTimeout(resolve,ms))}
async function withFileLock<T>(lockPath:string,action:()=>Promise<T>,options:LockOptions={}){const timeoutMs=options.timeoutMs??defaultLockTimeoutMs;const staleMs=options.staleMs??defaultStaleLockMs;const startedAt=Date.now();await mkdir(dirname(lockPath),{recursive:true,mode:0o700});for(;;){let handle;try{handle=await open(lockPath,"wx",0o600)}catch(error){const code=(error as NodeJS.ErrnoException).code;if(code!=="EEXIST")throw error;const entry=await existingFileKind(lockPath);if(!entry)continue;if(entry.isSymbolicLink())throw new Error("unsafe symlink state path");if(!entry.isFile())throw new Error("unsafe non-file state path");if(Date.now()-entry.mtimeMs>staleMs){await rm(lockPath,{force:true});continue}if(Date.now()-startedAt>=timeoutMs)throw new Error("run state is busy");await sleep(lockRetryMs);continue}try{await handle.writeFile(`${JSON.stringify({pid:process.pid,createdAt:new Date().toISOString()})}\n`);return await action()}finally{await handle.close();await rm(lockPath,{force:true})}}}
function parseJson(text:string,label:string){try{return JSON.parse(text) as unknown}catch{throw new Error(`invalid ${label} JSON`)}}
function validateRun(value:unknown,identity:RepositoryIdentity,expectedRunId:string):RiqorRun{if(!value||typeof value!=="object")throw new Error("invalid run record");const run=value as Partial<RiqorRun>;if(run.schemaVersion!==1)throw new Error("unsupported run schema");if(run.runId!==expectedRunId||run.repository?.rootDigest!==identity.rootDigest)throw new Error("run repository identity mismatch");if(!runIdPattern.test(run.runId)||!runIdPattern.test(run.runGroupId??""))throw new Error("invalid run record");if(typeof run.goal!=="string"||typeof run.createdAt!=="string"||typeof run.updatedAt!=="string")throw new Error("invalid run record");if(!Number.isInteger(run.nextSequence)||(run.nextSequence??0)<1)throw new Error("invalid run record");return Object.freeze(run as RiqorRun)}
function validateActivePointer(value:unknown):ActivePointer{if(!value||typeof value!=="object")throw new Error("invalid active run pointer");const pointer=value as Partial<ActivePointer>;if(pointer.schemaVersion!==1)throw new Error("unsupported active run schema");if(typeof pointer.runId!=="string"||!runIdPattern.test(pointer.runId))throw new Error("invalid active run pointer");return Object.freeze(pointer as ActivePointer)}
function validateTraceEvent(value:unknown,run:RiqorRun):RiqorTraceEvent{if(!value||typeof value!=="object")throw new Error("invalid trace event");const event=value as Partial<RiqorTraceEvent>;if(event.schemaVersion!==1)throw new Error("unsupported trace event schema");if(event.runId!==run.runId||event.runGroupId!==run.runGroupId)throw new Error("trace event run mismatch");if(!Number.isInteger(event.sequence)||(event.sequence??0)<1)throw new Error("invalid trace event sequence");return Object.freeze(event as RiqorTraceEvent)}
async function readRunFile(options:RunLocation){validateRootDigest(options.identity.rootDigest);validateRunId(options.runId);const path=join(runDirectory(options.stateRoot,options.identity.rootDigest,options.runId),"run.json");try{return validateRun(parseJson(await readTextFile(path),"run"),options.identity,options.runId)}catch(error){if((error as Error).message==="state file not found")throw new Error("run not found");throw error}}
async function appendEventLocked(options:AppendRunEventOptions,run:RiqorRun):Promise<{event:RiqorTraceEvent;run:RiqorRun}>{validateEventInput(options);const timestamp=(options.now??new Date()).toISOString();const sequence=run.nextSequence;const event:RiqorTraceEvent=Object.freeze({schemaVersion:1,eventId:(options.randomId??randomUUID)(),sequence,runId:run.runId,runGroupId:run.runGroupId,source:options.source,type:options.type,status:options.status,timestamp,...(options.subject===undefined?{}:{subject:options.subject}),...(options.digest===undefined?{}:{digest:options.digest}),...(options.evidenceRefs===undefined?{}:{evidenceRefs:[...options.evidenceRefs]}),...(options.metadata===undefined?{}:{metadata:{...options.metadata}})});const directory=runDirectory(options.stateRoot,options.identity.rootDigest,options.runId);const eventsPath=join(directory,"events.jsonl");await assertSafeRegularFile(eventsPath,true);await appendFile(eventsPath,`${JSON.stringify(event)}\n`,{encoding:"utf8",mode:0o600,flag:"a"});const updated:RiqorRun=Object.freeze({...run,status:options.nextStatus??run.status,nextSequence:sequence+1,updatedAt:timestamp});await writeJsonAtomic(join(directory,"run.json"),updated);return{event,run:updated}}
export async function readRun(options:RunLocation){return readRunFile(options)}
export async function readActiveRun(options:Omit<RunLocation,"runId">):Promise<RiqorRun|null>{validateRootDigest(options.identity.rootDigest);const path=activePath(options.stateRoot,options.identity.rootDigest);if(!await assertSafeRegularFile(path,true))return null;const pointer=validateActivePointer(parseJson(await readTextFile(path),"active run pointer"));const run=await readRunFile({...options,runId:pointer.runId});if(["completed","failed","abandoned"].includes(run.status)){await rm(path,{force:true});return null}return run}
export async function createRun(options:CreateRunOptions):Promise<RiqorRun>{validateRootDigest(options.identity.rootDigest);const goal=normalizeRunGoal(options.goal);const project=projectDirectory(options.stateRoot,options.identity.rootDigest);await mkdir(runsDirectory(options.stateRoot,options.identity.rootDigest),{recursive:true,mode:0o700});return withFileLock(join(project,".active.lock"),async()=>{const active=await readActiveRun({stateRoot:options.stateRoot,identity:options.identity});if(active)throw new Error(`an active run already exists: ${active.runId}`);const runId=(options.randomId??randomUUID)();validateRunId(runId);const parent=options.parentRunId?await readRunFile({stateRoot:options.stateRoot,identity:options.identity,runId:options.parentRunId}):null;const runGroupId=parent?.runGroupId??runId;const timestamp=(options.now??new Date()).toISOString();const directory=runDirectory(options.stateRoot,options.identity.rootDigest,runId);try{await mkdir(directory,{mode:0o700})}catch(error){if((error as NodeJS.ErrnoException).code==="EEXIST")throw new Error(`run already exists: ${runId}`);throw error}const initial:RiqorRun=Object.freeze({schemaVersion:1,runId,runGroupId,...(options.parentRunId===undefined?{}:{parentRunId:options.parentRunId}),goal,pathId:options.pathId,profileId:options.profileId,status:"active",repository:publicRepository(options.identity),nextSequence:1,createdAt:timestamp,updatedAt:timestamp});await writeJsonAtomic(join(directory,"run.json"),initial);await appendRunEvent({stateRoot:options.stateRoot,identity:options.identity,runId,source:"riqor",type:"run_started",status:"success",subject:options.pathId,metadata:{profile:options.profileId},now:options.now});await writeJsonAtomic(activePath(options.stateRoot,options.identity.rootDigest),{schemaVersion:1,runId} satisfies ActivePointer);return readRunFile({stateRoot:options.stateRoot,identity:options.identity,runId})})}
export async function appendRunEvent(options:AppendRunEventOptions):Promise<RiqorTraceEvent>{validateRunId(options.runId);const directory=runDirectory(options.stateRoot,options.identity.rootDigest,options.runId);return withFileLock(join(directory,".lock"),async()=>{const run=await readRunFile(options);return(await appendEventLocked(options,run)).event},{timeoutMs:options.lockTimeoutMs,staleMs:options.staleLockMs})}
export async function transitionRun(options:TransitionRunOptions):Promise<RiqorRun>{validateRunId(options.runId);const directory=runDirectory(options.stateRoot,options.identity.rootDigest,options.runId);return withFileLock(join(directory,".lock"),async()=>{const run=await readRunFile(options);const updated:RiqorRun=Object.freeze({...run,status:options.status,updatedAt:(options.now??new Date()).toISOString()});await writeJsonAtomic(join(directory,"run.json"),updated);return updated},{timeoutMs:options.lockTimeoutMs,staleMs:options.staleLockMs})}
export async function readRunEvents(options:RunLocation):Promise<RiqorTraceEvent[]>{const run=await readRunFile(options);const path=join(runDirectory(options.stateRoot,options.identity.rootDigest,options.runId),"events.jsonl");if(!await assertSafeRegularFile(path,true))return[];const lines=(await readFile(path,"utf8")).split("\n").filter(Boolean);const events=lines.map(line=>validateTraceEvent(parseJson(line,"trace event"),run));for(let index=0;index<events.length;index+=1)if(events[index]!.sequence!==index+1)throw new Error("trace event sequence gap");return events}
async function clearActivePointer(options:RunLocation){const project=projectDirectory(options.stateRoot,options.identity.rootDigest);await withFileLock(join(project,".active.lock"),async()=>{const path=activePath(options.stateRoot,options.identity.rootDigest);if(!await assertSafeRegularFile(path,true))return;const pointer=validateActivePointer(parseJson(await readTextFile(path),"active run pointer"));if(pointer.runId===options.runId)await rm(path,{force:true})})}
export async function completeRun(options:CompleteRunOptions):Promise<RiqorRun>{validateRunId(options.runId);const directory=runDirectory(options.stateRoot,options.identity.rootDigest,options.runId);const completed=await withFileLock(join(directory,".lock"),async()=>{const run=await readRunFile(options);if(run.status==="verification-pending")throw new Error("verification is still pending");if(run.status!=="active")throw new Error(`run is not active: ${run.status}`);const now=options.now??new Date();const result=await appendEventLocked({...options,source:"riqor",type:"run_completed",status:"success",nextStatus:"completed",now},run);const finalRun:RiqorRun=Object.freeze({...result.run,completedAt:now.toISOString()});await writeJsonAtomic(join(directory,"run.json"),finalRun);return finalRun},{timeoutMs:options.lockTimeoutMs,staleMs:options.staleLockMs});await clearActivePointer(options);return completed}
